In [90]:
# creating a data frame

In [91]:
import pandas as pd
import numpy as np

In [92]:
d={'name':['alisa','bobby','jodha','jack','raghu','cathrine','alisa','bobby','kumar','alex','cathrine','alisa'],
   'age':[26,24,23,22,23,24,26,24,22,23,24,24],
    'score':[85,63,55,74,31,77,85,63,42,62,89,77]}

In [93]:
df=pd.DataFrame(d)
df

name  age  score
0      alisa   26     85
1      bobby   24     63
2      jodha   23     55
3       jack   22     74
4      raghu   23     31
5   cathrine   24     77
6      alisa   26     85
7      bobby   24     63
8      kumar   22     42
9       alex   23     62
10  cathrine   24     89
11     alisa   24     77

In [94]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7      True
8     False
9     False
10    False
11    False
dtype: bool

In [95]:
df.duplicated("name")

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7      True
8     False
9     False
10     True
11     True
dtype: bool

In [96]:
df.drop_duplicates(['name'])

name  age  score
0     alisa   26     85
1     bobby   24     63
2     jodha   23     55
3      jack   22     74
4     raghu   23     31
5  cathrine   24     77
8     kumar   22     42
9      alex   23     62

In [97]:
from sklearn import datasets

In [98]:
iris=datasets.load_iris()

In [99]:
cancer=datasets.load_breast_cancer()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [100]:
cancer.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [101]:
cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [102]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [103]:
cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [104]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [105]:
x=iris.data
y=iris.target

In [106]:
x[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [107]:
x[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [108]:
y[:5]

array([0, 0, 0, 0, 0])

In [109]:
np.c_[x[:6], y[:6]]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ]])

In [110]:
data = np.c_[x, y]

In [111]:
column = ['sepal_Length', 'sepal_Width', 'petal_Length', 'petal_Width', 'class']
df=pd.DataFrame(data, columns=column)
df.head(4)

sepal_Length  sepal_Width  petal_Length  petal_Width  class
0           5.1          3.5           1.4          0.2    0.0
1           4.9          3.0           1.4          0.2    0.0
2           4.7          3.2           1.3          0.2    0.0
3           4.6          3.1           1.5          0.2    0.0

In [112]:
df['sepal_Length'].agg(['mean','max','count','median','std','var'])

mean        5.843333
max         7.900000
count     150.000000
median      5.800000
std         0.828066
var         0.685694
Name: sepal_Length, dtype: float64

In [113]:
replacements ={0:'setosa',1:'vesicolor',2:'virginica'}

In [114]:
df['class_rep'] = df['class'].map(replacements)

In [115]:
df.head()

sepal_Length  sepal_Width  petal_Length  petal_Width  class class_rep
0           5.1          3.5           1.4          0.2    0.0    setosa
1           4.9          3.0           1.4          0.2    0.0    setosa
2           4.7          3.2           1.3          0.2    0.0    setosa
3           4.6          3.1           1.5          0.2    0.0    setosa
4           5.0          3.6           1.4          0.2    0.0    setosa

In [116]:
df['class'].value_counts()

2.0    50
1.0    50
0.0    50
Name: class, dtype: int64

In [117]:
df.describe()

sepal_Length  sepal_Width  petal_Length  petal_Width       class
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    1.000000
std        0.828066     0.435866      1.765298     0.762238    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [118]:
df[['sepal_Length','petal_Length']].describe()

sepal_Length  petal_Length
count    150.000000    150.000000
mean       5.843333      3.758000
std        0.828066      1.765298
min        4.300000      1.000000
25%        5.100000      1.600000
50%        5.800000      4.350000
75%        6.400000      5.100000
max        7.900000      6.900000

In [119]:
df.loc[[1,10,5,8]]

sepal_Length  sepal_Width  petal_Length  petal_Width  class class_rep
1            4.9          3.0           1.4          0.2    0.0    setosa
10           5.4          3.7           1.5          0.2    0.0    setosa
5            5.4          3.9           1.7          0.4    0.0    setosa
8            4.4          2.9           1.4          0.2    0.0    setosa

In [120]:
df.loc[df['class_rep']=='setosa'].head(5)

sepal_Length  sepal_Width  petal_Length  petal_Width  class class_rep
0           5.1          3.5           1.4          0.2    0.0    setosa
1           4.9          3.0           1.4          0.2    0.0    setosa
2           4.7          3.2           1.3          0.2    0.0    setosa
3           4.6          3.1           1.5          0.2    0.0    setosa
4           5.0          3.6           1.4          0.2    0.0    setosa

In [121]:
df.loc[ df['class_rep']=='versicolor' , ['petal_Length', 'petal_Width']].mean()

petal_Length   NaN
petal_Width    NaN
dtype: float64

In [124]:
df.loc[ df['class_rep']=='versicolor' , ['petal_Length', 'petal_Width']].count()

petal_Length    0
petal_Width     0
dtype: int64

In [123]:
df['class_rep'].value_counts()

virginica    50
setosa       50
vesicolor    50
Name: class_rep, dtype: int64

In [125]:
# use of grouping
groups = df.groupby('class')

In [126]:
grp = df.groupby('petal_Width')

In [127]:
# use sum(), min(), max(), count()
groups.mean()

sepal_Length  sepal_Width  petal_Length  petal_Width
class                                                      
0.0           5.006        3.428         1.462        0.246
1.0           5.936        2.770         4.260        1.326
2.0           6.588        2.974         5.552        2.026

In [129]:
groups.agg(['mean', 'min', 'max', 'count'])
grp.agg(['mean','min','max','count'])

sepal_Length                 sepal_Width                  \
                    mean  min  max count        mean  min  max count   
petal_Width                                                            
0.1             4.820000  4.3  5.2     5    3.360000  3.0  4.1     5   
0.2             4.972414  4.4  5.8    29    3.379310  2.9  4.2    29   
0.3             4.971429  4.5  5.7     7    3.328571  2.3  3.8     7   
0.4             5.300000  5.0  5.7     7    3.785714  3.4  4.4     7   
0.5             5.100000  5.1  5.1     1    3.300000  3.3  3.3     1   
0.6             5.000000  5.0  5.0     1    3.500000  3.5  3.5     1   
1.0             5.414286  4.9  6.0     7    2.371429  2.0  2.7     7   
1.1             5.400000  5.1  5.6     3    2.466667  2.4  2.5     3   
1.2             5.780000  5.5  6.1     5    2.740000  2.6  3.0     5   
1.3             5.884615  5.5  6.6    13    2.746154  2.3  3.0    13   
1.4             6.325000  5.2  7.0     8    2.912500  2.6  3.2     8   
1.5             6.183333  5.4  6.9    12    2.816667  2.2  3.2    12   
1.6             6.375000  6.0  7.2     4    3.100000  2.7  3.4     4   
1.7             5.800000  4.9  6.7     2    2.750000  2.5  3.0     2   
1.8             6.400000  5.9  7.3    12    2.941667  2.5  3.2    12   
1.9             6.340000  5.8  7.4     5    2.680000  2.5  2.8     5   
2.0             6.650000  5.6  7.9     6    3.016667  2.5  3.8     6   
2.1             6.916667  6.4  7.6     6    3.033333  2.8  3.3     6   
2.2             6.866667  6.4  7.7     3    3.200000  2.8  3.8     3   
2.3             6.912500  6.2  7.7     8    3.087500  2.6  3.4     8   
2.4             6.266667  5.8  6.7     3    3.100000  2.8  3.4     3   
2.5             6.733333  6.3  7.2     3    3.400000  3.3  3.6     3   

            petal_Length                     class                  
                    mean  min  max count      mean  min  max count  
petal_Width                                                         
0.1             1.380000  1.1  1.5     5  0.000000  0.0  0.0     5  
0.2             1.444828  1.0  1.9    29  0.000000  0.0  0.0    29  
0.3             1.428571  1.3  1.7     7  0.000000  0.0  0.0     7  
0.4             1.571429  1.3  1.9     7  0.000000  0.0  0.0     7  
0.5             1.700000  1.7  1.7     1  0.000000  0.0  0.0     1  
0.6             1.600000  1.6  1.6     1  0.000000  0.0  0.0     1  
1.0             3.628571  3.3  4.1     7  1.000000  1.0  1.0     7  
1.1             3.566667  3.0  3.9     3  1.000000  1.0  1.0     3  
1.2             4.240000  3.9  4.7     5  1.000000  1.0  1.0     5  
1.3             4.176923  3.6  4.6    13  1.000000  1.0  1.0    13  
1.4             4.637500  3.9  5.6     8  1.125000  1.0  2.0     8  
1.5             4.658333  4.2  5.1    12  1.166667  1.0  2.0    12  
1.6             5.025000  4.5  5.8     4  1.250000  1.0  2.0     4  
1.7             4.750000  4.5  5.0     2  1.500000  1.0  2.0     2  
1.8             5.333333  4.8  6.3    12  1.916667  1.0  2.0    12  
1.9             5.320000  5.0  6.1     5  2.000000  2.0  2.0     5  
2.0             5.550000  4.9  6.7     6  2.000000  2.0  2.0     6  
2.1             5.783333  5.4  6.6     6  2.000000  2.0  2.0     6  
2.2             6.033333  5.6  6.7     3  2.000000  2.0  2.0     3  
2.3             5.700000  5.1  6.9     8  2.000000  2.0  2.0     8  
2.4             5.433333  5.1  5.6     3  2.000000  2.0  2.0     3  
2.5             5.933333  5.7  6.1     3  2.000000  2.0  2.0     3

In [130]:
df.head()

sepal_Length  sepal_Width  petal_Length  petal_Width  class class_rep
0           5.1          3.5           1.4          0.2    0.0    setosa
1           4.9          3.0           1.4          0.2    0.0    setosa
2           4.7          3.2           1.3          0.2    0.0    setosa
3           4.6          3.1           1.5          0.2    0.0    setosa
4           5.0          3.6           1.4          0.2    0.0    setosa

In [131]:
D ={'unit':['UD', 'UD', 'UD', 'UD', 'ud','uD'],
    'N-D':  [ 'Q1', 'Q2', 'Q3', 'Q4','Q5','Q6'],
 'num' : [ -1.48, 1.7, -6.18, 0.25, 'weird', 0.25]

}

In [134]:
dff=pd.DataFrame(D)
dff

unit N-D    num
0   UD  Q1  -1.48
1   UD  Q2    1.7
2   UD  Q3  -6.18
3   UD  Q4   0.25
4   ud  Q5  weird
5   uD  Q6   0.25

In [136]:
type(df)
type(dff)

pandas.core.frame.DataFrame

In [137]:
dff['num'].str.istitle()

0      NaN
1      NaN
2      NaN
3      NaN
4    False
5      NaN
Name: num, dtype: object

In [138]:
dff['num'].str.isdecimal()

0      NaN
1      NaN
2      NaN
3      NaN
4    False
5      NaN
Name: num, dtype: object

In [141]:
dff['unit'].str.isupper()

0     True
1     True
2     True
3     True
4    False
5    False
Name: unit, dtype: bool

In [142]:
dff['unit'].str.upper()

0    UD
1    UD
2    UD
3    UD
4    UD
5    UD
Name: unit, dtype: object

In [143]:
dff['unit'] = dff['unit'].str.upper()

In [144]:
dff

unit N-D    num
0   UD  Q1  -1.48
1   UD  Q2    1.7
2   UD  Q3  -6.18
3   UD  Q4   0.25
4   UD  Q5  weird
5   UD  Q6   0.25

In [149]:
nba = pd.read_csv(r"C:\Users\Surjeet\Desktop\all_files\datasets\auto-specs.csv")

In [151]:
nba.shape

(204, 26)

In [152]:
nba.head(5)

3    ?  alfa-romero  gas  std   two  convertible  rwd  front  88.60  ...  \
0  3    ?  alfa-romero  gas  std   two  convertible  rwd  front   88.6  ...   
1  1    ?  alfa-romero  gas  std   two    hatchback  rwd  front   94.5  ...   
2  2  164         audi  gas  std  four        sedan  fwd  front   99.8  ...   
3  2  164         audi  gas  std  four        sedan  4wd  front   99.4  ...   
4  2    ?         audi  gas  std   two        sedan  fwd  front   99.8  ...   

   130  mpfi  3.47  2.68  9.00  111  5000  21  27  13495  
0  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500  
1  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500  
2  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950  
3  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450  
4  136  mpfi  3.19  3.40   8.5  110  5500  19  25  15250  

[5 rows x 26 columns]

In [153]:
nba.isnull().sum()

3              0
?              0
alfa-romero    0
gas            0
std            0
two            0
convertible    0
rwd            0
front          0
88.60          0
168.80         0
64.10          0
48.80          0
2548           0
dohc           0
four           0
130            0
mpfi           0
3.47           0
2.68           0
9.00           0
111            0
5000           0
21             0
27             0
13495          0
dtype: int64

In [154]:
nba.count()

3              204
?              204
alfa-romero    204
gas            204
std            204
two            204
convertible    204
rwd            204
front          204
88.60          204
168.80         204
64.10          204
48.80          204
2548           204
dohc           204
four           204
130            204
mpfi           204
3.47           204
2.68           204
9.00           204
111            204
5000           204
21             204
27             204
13495          204
dtype: int64